/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BtcRouteImport } from './routes/btc'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as EthRouteImport } from './routes/eth'
import { Route as FilingsRouteImport } from './routes/filings'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as LabRouteImport } from './routes/lab'
import { Route as Mag7RouteImport } from './routes/mag7'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NqRouteImport } from './routes/nq'
import { Route as OilRouteImport } from './routes/oil'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as SolRouteImport } from './routes/sol'
import { Route as SpxRouteImport } from './routes/spx'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as VixRouteImport } from './routes/vix'
import { Route as XlmRouteImport } from './routes/xlm'
import { Route as XrpRouteImport } from './routes/xrp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BtcRoute = BtcRouteImport.update({
  id: '/btc',
  path: '/btc',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const EthRoute = EthRouteImport.update({
  id: '/eth',
  path: '/eth',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingsRoute = FilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const Mag7Route = Mag7RouteImport.update({
  id: '/mag7',
  path: '/mag7',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NqRoute = NqRouteImport.update({
  id: '/nq',
  path: '/nq',
  getParentRoute: () => rootRouteImport,
} as any)
const OilRoute = OilRouteImport.update({
  id: '/oil',
  path: '/oil',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const SolRoute = SolRouteImport.update({
  id: '/sol',
  path: '/sol',
  getParentRoute: () => rootRouteImport,
} as any)
const SpxRoute = SpxRouteImport.update({
  id: '/spx',
  path: '/spx',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const VixRoute = VixRouteImport.update({
  id: '/vix',
  path: '/vix',
  getParentRoute: () => rootRouteImport,
} as any)
const XlmRoute = XlmRouteImport.update({
  id: '/xlm',
  path: '/xlm',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpRoute = XrpRouteImport.update({
  id: '/xrp',
  path: '/xrp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/btc': typeof BtcRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/eth': typeof EthRoute
  '/filings': typeof FilingsRoute
  '/gold': typeof GoldRoute
  '/lab': typeof LabRoute
  '/mag7': typeof Mag7Route
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/nq': typeof NqRoute
  '/oil': typeof OilRoute
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/silver': typeof SilverRoute
  '/socials': typeof SocialsRoute
  '/sol': typeof SolRoute
  '/spx': typeof SpxRoute
  '/truth': typeof TruthRoute
  '/updates': typeof UpdatesRoute
  '/vix': typeof VixRoute
  '/xlm': typeof XlmRoute
  '/xrp': typeof XrpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/btc': typeof BtcRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/eth': typeof EthRoute
  '/filings': typeof FilingsRoute
  '/gold': typeof GoldRoute
  '/lab': typeof LabRoute
  '/mag7': typeof Mag7Route
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/nq': typeof NqRoute
  '/oil': typeof OilRoute
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/silver': typeof SilverRoute
  '/socials': typeof SocialsRoute
  '/sol': typeof SolRoute
  '/spx': typeof SpxRoute
  '/truth': typeof TruthRoute
  '/updates': typeof UpdatesRoute
  '/vix': typeof VixRoute
  '/xlm': typeof XlmRoute
  '/xrp': typeof XrpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/btc': typeof BtcRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/eth': typeof EthRoute
  '/filings': typeof FilingsRoute
  '/gold': typeof GoldRoute
  '/lab': typeof LabRoute
  '/mag7': typeof Mag7Route
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/nq': typeof NqRoute
  '/oil': typeof OilRoute
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/silver': typeof SilverRoute
  '/socials': typeof SocialsRoute
  '/sol': typeof SolRoute
  '/spx': typeof SpxRoute
  '/truth': typeof TruthRoute
  '/updates': typeof UpdatesRoute
  '/vix': typeof VixRoute
  '/xlm': typeof XlmRoute
  '/xrp': typeof XrpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/btc'
    | '/calendar'
    | '/crypto'
    | '/eth'
    | '/filings'
    | '/gold'
    | '/lab'
    | '/mag7'
    | '/more'
    | '/news'
    | '/nq'
    | '/oil'
    | '/screener'
    | '/search'
    | '/sessions'
    | '/silver'
    | '/socials'
    | '/sol'
    | '/spx'
    | '/truth'
    | '/updates'
    | '/vix'
    | '/xlm'
    | '/xrp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/btc'
    | '/calendar'
    | '/crypto'
    | '/eth'
    | '/filings'
    | '/gold'
    | '/lab'
    | '/mag7'
    | '/more'
    | '/news'
    | '/nq'
    | '/oil'
    | '/screener'
    | '/search'
    | '/sessions'
    | '/silver'
    | '/socials'
    | '/sol'
    | '/spx'
    | '/truth'
    | '/updates'
    | '/vix'
    | '/xlm'
    | '/xrp'
  id:
    | '__root__'
    | '/'
    | '/btc'
    | '/calendar'
    | '/crypto'
    | '/eth'
    | '/filings'
    | '/gold'
    | '/lab'
    | '/mag7'
    | '/more'
    | '/news'
    | '/nq'
    | '/oil'
    | '/screener'
    | '/search'
    | '/sessions'
    | '/silver'
    | '/socials'
    | '/sol'
    | '/spx'
    | '/truth'
    | '/updates'
    | '/vix'
    | '/xlm'
    | '/xrp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BtcRoute: typeof BtcRoute
  CalendarRoute: typeof CalendarRoute
  CryptoRoute: typeof CryptoRoute
  EthRoute: typeof EthRoute
  FilingsRoute: typeof FilingsRoute
  GoldRoute: typeof GoldRoute
  LabRoute: typeof LabRoute
  Mag7Route: typeof Mag7Route
  MoreRoute: typeof MoreRoute
  NewsRoute: typeof NewsRoute
  NqRoute: typeof NqRoute
  OilRoute: typeof OilRoute
  ScreenerRoute: typeof ScreenerRoute
  SearchRoute: typeof SearchRoute
  SessionsRoute: typeof SessionsRoute
  SilverRoute: typeof SilverRoute
  SocialsRoute: typeof SocialsRoute
  SolRoute: typeof SolRoute
  SpxRoute: typeof SpxRoute
  TruthRoute: typeof TruthRoute
  UpdatesRoute: typeof UpdatesRoute
  VixRoute: typeof VixRoute
  XlmRoute: typeof XlmRoute
  XrpRoute: typeof XrpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/btc': {
      id: '/btc'
      path: '/btc'
      fullPath: '/btc'
      preLoaderRoute: typeof BtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eth': {
      id: '/eth'
      path: '/eth'
      fullPath: '/eth'
      preLoaderRoute: typeof EthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filings': {
      id: '/filings'
      path: '/filings'
      fullPath: '/filings'
      preLoaderRoute: typeof FilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mag7': {
      id: '/mag7'
      path: '/mag7'
      fullPath: '/mag7'
      preLoaderRoute: typeof Mag7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nq': {
      id: '/nq'
      path: '/nq'
      fullPath: '/nq'
      preLoaderRoute: typeof NqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oil': {
      id: '/oil'
      path: '/oil'
      fullPath: '/oil'
      preLoaderRoute: typeof OilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol': {
      id: '/sol'
      path: '/sol'
      fullPath: '/sol'
      preLoaderRoute: typeof SolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spx': {
      id: '/spx'
      path: '/spx'
      fullPath: '/spx'
      preLoaderRoute: typeof SpxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vix': {
      id: '/vix'
      path: '/vix'
      fullPath: '/vix'
      preLoaderRoute: typeof VixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xlm': {
      id: '/xlm'
      path: '/xlm'
      fullPath: '/xlm'
      preLoaderRoute: typeof XlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrp': {
      id: '/xrp'
      path: '/xrp'
      fullPath: '/xrp'
      preLoaderRoute: typeof XrpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BtcRoute: BtcRoute,
  CalendarRoute: CalendarRoute,
  CryptoRoute: CryptoRoute,
  EthRoute: EthRoute,
  FilingsRoute: FilingsRoute,
  GoldRoute: GoldRoute,
  LabRoute: LabRoute,
  Mag7Route: Mag7Route,
  MoreRoute: MoreRoute,
  NewsRoute: NewsRoute,
  NqRoute: NqRoute,
  OilRoute: OilRoute,
  ScreenerRoute: ScreenerRoute,
  SearchRoute: SearchRoute,
  SessionsRoute: SessionsRoute,
  SilverRoute: SilverRoute,
  SocialsRoute: SocialsRoute,
  SolRoute: SolRoute,
  SpxRoute: SpxRoute,
  TruthRoute: TruthRoute,
  UpdatesRoute: UpdatesRoute,
  VixRoute: VixRoute,
  XlmRoute: XlmRoute,
  XrpRoute: XrpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
